# fly.toml app configuration file generated for myges-discord-bot on 2026-01-21T01:04:48+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'myges-discord-bot'
primary_region = 'cdg'



[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
